### ISSUE TITLE
Why Public Thread users get's removed when the app is closed, how to keep those users in the public thread ?

### ISSUE THREAD

**Issue by abdullahalshafi** [chat-sdk/docs#10]

**Comment by abdullahalshafi** [comment]
Hi thank you so much for your reply, But is there any way i can keep the users and will users get notified when there is a new message ?

**Comment by bensmiley** [comment]
Yes, you can use this parameter:
```
config.pushNotificationsForPublicChatRoomsEnabled(true);
```
During setup. 
You would also need to subclass the `ChatActivity` and set:

```
protected boolean removeUserFromChatOnExit = false;
```

You can see how to subclass that class [here](https://github.com/chat-sdk/docs#using-the-interface-manager).

**Comment by abdullahalshafi** [comment]
removeUserFromChatOnExit = false not removing users when closing the ChatActivity But it eventually removes the user when the app is closed from recent
