### ISSUE TITLE
How to display unread messages badge

### ISSUE THREAD

**Issue by ZaroonRashid** [chat-sdk/docs#17]
I unable to find, how can I show unread messages badge on button which open ChatActivity.

**Comment by bensmiley** [comment]
@ZaroonRashid if you have the thread ID you can do it like this:

```
Thread thread = ChatSDK.db().fetchThreadWithID("id");
thread.getUnreadMessagesCount();
```

**Comment by ZaroonRashid** [comment]
id will be threadEntityId ??
I am getting error here ... getting invalid id

**Comment by bensmiley** [comment]
Yes the id is the thread entity id. What is the error you're getting?

**Comment by ZaroonRashid** [comment]
I am saving in my dg as string and when convert it to Long (Long.parseLong(string)) ...
getting error of invalid long ...

**Comment by bensmiley** [comment]
You don't need to convert it to a long. The entity ID should be a string.

**Comment by ZaroonRashid** [comment]
![issue](https://user-images.githubusercontent.com/29312919/85744524-66cf8780-b71e-11ea-815c-aef998303acd.png)

**Comment by bensmiley** [comment]
Ah ok, try this:

```
            ChatSDK.db().fetchThreadWithEntityID("id");
```

**Comment by ZaroonRashid** [comment]
![image](https://user-images.githubusercontent.com/29312919/85810184-a7a5bb80-b773-11ea-9554-b4426baa1834.png)

**Comment by ZaroonRashid** [comment]
thanks you so much @bensmiley ....
