### ISSUE TITLE
android - The  AccountDetails functions are statics

### ISSUE THREAD

**Issue by yadidl** [chat-sdk/docs#3]
Should fix this way:
-AccountDetails details = new AccountDetails.token("Your token");
+AccountDetails details = AccountDetails.token("Your token");

To keep doc more clear i think it will be better to update those lines too:
-AccountDetails details = username("some.email@domain.com", "some password");
+AccountDetails details = AccountDetails.username("some.email@domain.com", "some password");

-AccountDetails details = signUp("Joe", "Joe123");
+AccountDetails details = AccountDetails.signUp("Joe", "Joe123");

**Comment by deadpool9987** [comment]
Hi 

Is this fixed? @yadidl where you able to successfully register a user on firebase. Please let me know I am not able to register a user on firebase

**Comment by bensmiley** [comment]
Docs have been updated.

**Comment by bensmiley** [comment]
These are the new docs: https://chat-sdk.gitbook.io/chat-sdk/
