### ISSUE TITLE
Problem with sending message with bMessageTypeCustom

### ISSUE THREAD

**Issue by tranc4mer** [chat-sdk/docs#5]
Normally I can send text message to tread by 
 `[NM.core sendMessageWithText:@"Some text" withThreadEntityID:thread.entityID];`
but in my progect I want to make custom cell for layout massage basic on info in text field of message
in this case I should set message to bMessageTypeCustom
how in Docs example:
```
id<PMessage> message = [[BStorageManager sharedManager].a createEntity:bMessageEntity];
            message.type = @(bMessageTypeCustom);
            [message setText:[NSString stringWithString:@"MyIdentifierText-CodeForCustomCellInitiation"]];
```
then I got method for send message 
```
[NM.core sendMessage:message];
```
but I can't set message tread 
in documentation ic next:
```
// Use thread setMessage instead
//-(void) setThread: (id<PThread>) thread;
-(id<PThread>) thread;
```
method `sendThread` is commented and it noted to use `setMessage` method that is absent in ChatSDK

How to send message with bMessageTypeCustom. ???

**Comment by bensmiley** [comment]
You would need to get the thread that you want to add the message to:
```
[thread addMessage: message]
```
